### ISSUE TITLE
Certonly can't be used without extra packages

### ISSUE THREAD

**Issue by sulliops** [zerossl/certbot-zerossl#2]
The wrapper doesn't allow for the `certonly` argument to be used unless the following packages are also installed:

```
python-certbot-apache
augeas-lenses
libaugeas0
python-augeas
```

Users without automatically detected web servers (or those wishing to just generate certs) will need to install these packages in order to use `certonly` with the wrapper:

```
sudo apt-get update && sudo apt-get install python-certbot-apache
```

This should be added to the README.md documentation.

**Comment by DoubleMalt** [comment]
Thanks for testing our script and reporting the issue!

The problem you describe is also true for certbot proper. Maybe we should point out explicitely to follow the instructions on https://certbot.eff.org/ to install certbot.

Every argument and mode you can use with your installed certbot can also be used with our wrapper.

**Comment by sulliops** [comment]
Gotcha, I was running on a fresh install of certbot from `apt-get`, apparently their `snap` repository also installs related packages. The documentation should definitely be updated!
